### ISSUE TITLE
Set kirby options in config.php from .env

### ISSUE THREAD

**Issue by philipmarnef** [bnomei/kirby3-dotenv#6]
Tried to set default options (like `url`) in Kirby's `config.php` with your plugin, but this seems not possible. Correct? 

Kinda hard to debug because errors in `config.php` means the `debug` option falls back to `false` and nothing gets logged.

**Comment by bnomei** [comment]
sadly... yes. the config is loaded before any plugins and their code.
i have not checked but most core values do not support a callback (closure) as value.

since the config is plain php you could use composer to require the used lib and manually load the dot env file.

**Comment by moevbiz** [comment]
> since the config is plain php you could use composer to require the used lib and manually load the dot env file.

Could you maybe give an example of how this works? I need to set some core options (email) and can't have passwords etc show up in a config file on my git repository…

**Comment by philipmarnef** [comment]
@moevbiz This plugin uses [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) under the hood, which should be loaded with composer autoload at this point I think. If not you have to load it manually (not sure what's the best way to do this).

Then something like this on top of your `config.php` should work (not tested):

```php
// load the .env with the original Dotenv class
$dotenv = new \Dotenv\Dotenv('path/to/.env');
$dotenv->load();
// get your variable from .env for use in the config array
$email = $_ENV['EMAIL'];
```

**Comment by moevbiz** [comment]
@philipmarnef this works, thanks!
The path I used for a default Kirby folder setup with `.env` being at the document root is `__DIR__ . '/../..'` (don't add the .env filename).
I tried using `kirby()->root('index')` as well but the plugin doesn't seem to like that.

**Comment by bnomei** [comment]
can be done in v2. see https://github.com/bnomei/kirby3-dotenv/tree/master/tests/site/config

**Comment by antoineCantoro** [comment]
Hello, I ran into the same issue with v5.0.1 in my config.php (Kirby 5.2.5, PHP 8.2). 

I fixed it with the following lines:
$root = dirname(__DIR__ , 2); // root of my project
$dotenv = Dotenv\Dotenv::createImmutable($root);
$dotenv->safeLoad();

I also tried using the loadenv() method as mentioned in the documentation, but it didn’t work for me.
