### ISSUE TITLE
`filename` option doesn't seem to be used by plugin

### ISSUE THREAD

**Issue by PaulMorel** [bnomei/kirby3-dotenv#8]
I have a site with a `.env` file and a `.env.prod` file. The `.env.prod` file never gets loaded in the appropriate context. I'm using Kirby's multi-environment config feature.

I've noticed that the `filename` option never gets used in the plugin, while it most likely should be used when instantiating the `DotEnv` class. 

https://github.com/bnomei/kirby3-dotenv/blob/430196107ed6083d554e4172e75e9fbee3e014db/classes/DotEnv.php#L39

As you can see in the class' constructor, you can set your filename.

https://github.com/bnomei/kirby3-dotenv/blob/430196107ed6083d554e4172e75e9fbee3e014db/vendor/vlucas/phpdotenv/src/Dotenv.php#L37-L41

For the time being I've patched my install of the plugin, but I think this should be included? What do you think?

I could submit a PR if you'd like.

**Comment by bnomei** [comment]
sorry for the late reply... i am in parental leave. sure, please do submit a PR and i will take a look.

**Comment by bnomei** [comment]
renamed setting to `file` and will be used with plugin v2. also added proper multi-environment support.
